#!/bin/sh


set +x


sorce_dir="/home/manoj/test123"
# Parent backup directory
backup__dir="/tmp"

# Directories to backup
ls /home/manoj/test123 | sed 's/\s\+/\n/g'

# Check and create backup directory
backup_date=`date +%Y_%m_%d_%H_%M`
backup_path=${backup_dir}/${backup_date}
mkdir -p $backup_path

# Directories to backup
ls /home/manoj/test123 | sed 's/\s\+/\n/g' > /home/backup_me

#declare -a output

output=`cat "/home/backup_me"`

for directory  in "${output[@]}"

do

cp -r $sorce_dir/$directory $backup_path
 
done


# Perform backup
#for directory in $backup_me
#do
#        archive_name=`echo ${directory} | sed s/^\\\/// | sed s/\\\//_/g`
#        tar pcfzP ${backup_dir}/${archive_name}.tgz ${directory} 2>&1 | tee > ${backup_dir}/${archive_name}.log
#done
