# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 06:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0010_auto_20160301_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True), blank=True, null=True, size=2),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='product',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='short_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='web_page',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
