# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 06:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0011_auto_20160301_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='phone',
            field=django.contrib.postgres.fields.ArrayField(base_field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True), blank=True, null=True, size=3),
        ),
    ]
