# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 02:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160220_1138'),
        ('mentions', '0015_auto_20160302_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_networks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('search_terms', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentions.Merchant')),
            ],
            options={
                'verbose_name': 'Tracker',
                'ordering': ('-pk',),
                'verbose_name_plural': 'Trackers',
            },
        ),
    ]
