# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0022_auto_20160318_0733'),
        ('mentions', '0022_auto_20160317_0735'),
    ]

    operations = [
    ]
