# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0024_auto_20160322_0635'),
        ('mentions', '0024_auto_20160322_0642'),
    ]

    operations = [
    ]
