# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mentions', '0025_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=16, null=True,
                                   verbose_name='MCC'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='rating',
        #     unique_together=set([('merchant', 'week', 'month', 'year')]),
        # ),
        # migrations.AlterIndexTogether(
        #     name='rating',
        #     index_together=set([('merchant', 'week', 'month', 'year')]),
        # ),
    ]
