# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0033_auto_20160422_0346'),
    ]

    operations = [

        migrations.AddField(
            model_name='mention',
            name='text_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),

        migrations.AlterUniqueTogether(
            name='mention',
            unique_together=set([('merchant', 'text_hash')]),
        ),
    ]
