# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 08:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0036_auto_20160803_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), blank=True, default=['www.yelp.com', 'www.facebook.com', 'plus.google.com', 'www.ripoffreport.com', 'www.bbb.org'], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mention',
            name='origin_site',
            field=models.CharField(blank=True, choices=[('www.yelp.com', 'www.yelp.com'), ('www.facebook.com', 'www.facebook.com'), ('plus.google.com', 'plus.google.com'), ('www.ripoffreport.com', 'www.ripoffreport.com'), ('www.bbb.org', 'www.bbb.org')], max_length=32, null=True),
        )
    ]
