# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mentions', '0006_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'high'),
                                                        ('middle', 'middle'),
                                                        ('low', 'low')],
                                   max_length=10, null=True),
        ),
    ]
