# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0014_merchant_ceo'),
    ]

    operations = [

        migrations.AddField(
            model_name='merchant',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
