# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0017_merge'),
    ]

    operations = [

        migrations.AlterField(
            model_name='rating',
            name='mentions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='neg_mentions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='open_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='pos_mentions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='solved_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='mentions.Merchant'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='solved_complaints',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='unresolved_complaints',
        ),
        # migrations.AlterUniqueTogether(
        #     name='rating',
        #     unique_together=set([('merchant', 'week', 'year')]),
        # ),
        # migrations.AlterIndexTogether(
        #     name='rating',
        #     index_together=set([('merchant', 'week', 'year')]),
        # ),
    ]
