# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 06:35
from __future__ import unicode_literals, with_statement

import json
import os

from django.conf import settings
from django.db import migrations, models


def load_mcc(apps, shema_editor):
    """Imports MCC codes from dump to DB.

    The function has to load data from JSON file.

    JSON data format like this:
      [
        {
          'code': 1234,
          'title': 'Industry title'
        },
      ]

    Imports `code` to Category.code and `title` to Category.title.

    Args:
      apps: versioned app registry.
      shema_editor: instance of the backend's SchemaEditor.

    """
    path = os.path.join(settings.BASE_DIR, 'apps/mentions/fixtures/mcc.json')

    try:
        with open(path) as f:
            data = json.loads(f.read())
    except IOError:
        data = []

    Category = apps.get_model("mentions", "Category")

    for d in data:
        Category.objects.create(code=d['code'], name=d['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0023_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='MCC'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(load_mcc),
    ]
