# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0026_auto_20160324_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('google_responce', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_results', to='mentions.Merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
