# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0027_auto_20160325_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryresults',
            name='semantria_responce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryresults',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_results', to='mentions.Merchant'),
        ),
    ]
