# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0028_auto_20160328_0401'),
    ]

    operations = [

        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='official_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        # migrations.AlterUniqueTogether(
        #     name='rating',
        #     unique_together=set([]),
        # ),
        migrations.AlterIndexTogether(
            name='mention',
            index_together=set([('merchant', 'status')]),
        ),
    ]
