# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 06:01
from __future__ import unicode_literals, with_statement

import json
import os

from django.conf import settings
from django.db import migrations, models


def unfold_categories(apps, shema_editor):
    """Update industries.

    Unfolding. Create Category for all in-array categories.

    Args:
      apps: versioned app registry.
      shema_editor: instance of the backend's SchemaEditor.

    """
    Category = apps.get_model("mentions", "Category")

    for category in Category.objects.extra(where=["cardinality(codes) > 1"]):
        for code in category.codes[1:]:
            Category.objects.create(code=code, codes=[code],
                                    name=category.name)


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0031_auto_20160407_0738'),
    ]

    operations = [
        migrations.RunPython(unfold_categories,
                             reverse_code=migrations.RunPython.noop),
    ]
