# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 05:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0035_auto_20160601_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='search_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
