# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mentions', '0002_auto_20160203_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mention',
            options={'ordering': ('-created',),
                     'permissions': ('veiw_merchant', 'Can_view_merchant')},
        ),
    ]
