# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0008_auto_20160210_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='web_page',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'High'), (1, 'Middle'), (2, 'Low')], null=True),
        ),
    ]
