# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0016_auto_20160309_0223'),
        ('mentions', '0016_auto_20160309_1036'),
    ]

    operations = [
    ]
