# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mentions', '0021_auto_20160315_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=16, blank=True, null=True,
                                   unique=True, verbose_name='SIC'),
        ),
    ]
