# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 07:38
from __future__ import unicode_literals, with_statement

import json
import os

from django.conf import settings
from django.db import migrations, models


def update_mcc(apps, shema_editor):
    """Imports MCC codes from dump to DB.

    The function has to update exists data: will add range os codes for new
    logic of categories.

    JSON data format like this:
      [
        {
          'codes': ['1234', '4567'],
          'name': 'Category name',
          'reportable': 0
        },
      ]

    Update `name`, set `codes` range codes and set `reportable` for exist 
    Categories.

    Args:
      apps: versioned app registry.
      shema_editor: instance of the backend's SchemaEditor.

    """
    path = os.path.join(settings.BASE_DIR, 'apps/mentions/fixtures/mcc.2.json')

    try:
        with open(path) as f:
            data = json.loads(f.read())
    except IOError:
        data = []

    Category = apps.get_model("mentions", "Category")

    for row in data:
        obj = Category.objects.filter(code=row['codes'][0])[:1]
        codes = row['codes']
        # if codes are twice, get range between these
        if len(codes) == 2:
            codes = list(range(int(codes[0]), int(codes[1])+1))
        # if lookup has object, update this object
        if obj:
            category = obj[0]
            category.name = row['name']
            category.codes = codes
            category.reportable = row['reportable']
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0030_auto_20160407_0728'),
    ]

    operations = [
        migrations.RunPython(update_mcc, 
                             reverse_code=migrations.RunPython.noop),
    ]
