# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0032_auto_20160412_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'code'), 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ('official_name',), 'verbose_name': 'Merchant', 'verbose_name_plural': 'Merchants'},
        ),
        migrations.AlterField(
            model_name='mention',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='mentions.Merchant'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='mentions.Category'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mentions.Merchant'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='mentions.Mention'),
        ),
    ]
