# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 12:03
from __future__ import unicode_literals

import apps.users.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.users.models.upload_user_media_to),
        ),
    ]
