# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160216_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='merchant',
            new_name='merchants',
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('i', 'ISO'), ('m', 'Merchant')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_type',
            field=models.CharField(choices=[('g', 'Google'), ('s', 'Semantria')], max_length=1),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, choices=[('a', 'Admin'), ('u', 'User')], max_length=1, null=True),
        ),
    ]
