# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160220_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('company_name',), 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='merchants',
            field=models.ManyToManyField(blank=True, db_index=True, to='mentions.Merchant'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='account',
            field=models.ManyToManyField(blank=True, db_index=True, to='users.Account'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Account'),
        ),
        migrations.AlterIndexTogether(
            name='apikey',
            index_together=set([('api_type', 'token', 'secret')]),
        ),
    ]
