# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 05:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0013_auto_20160302_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='ceo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
