# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 07:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0029_auto_20160328_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=4, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='category',
            name='reportable',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No1.6041-3(c)')], default=True),
        ),
    ]
