# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentions', '0034_auto_20160429_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='origin_site',
            field=models.CharField(blank=True, choices=[('www.yelp.com', 'www.yelp.com'), ('www.facebook.com', 'www.facebook.com'), ('www.ripoffreport.com', 'www.ripoffreport.com'), ('plus.google.com', 'plus.google.com'), ('www.bbb.org', 'www.bbb.org')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='exclude_words',
            field=models.CharField(blank=True, help_text='Comma-separated', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
